---

version: "3.3"

services:

  grafana:
    image: grafana/grafana:5.2.2
    ports:
      - 9000:9000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      back-tier:
        aliases:
          - grafana
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500m
      restart_policy:
        condition: on-failure
        delay: 10s

networks:
  back-tier:
    external: true

volumes:
  grafanadata:
    external: true
