---

version: "3.3"

services:

  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    networks:
      back-tier:
        aliases:
         - verdaccio
    volumes:
      - verdacciodata:/verdaccio/storage
      - ./config:/verdaccio/conf
    # configs:
    # # to avoid changes to the original verdaccio image, we import the healthcheck script using configs
    #   - verdaccio-healthcheck
    # healthcheck:
    #   test: ["CMD", "bash", "/verdaccio-healthcheck"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300m
      restart_policy:
        condition: on-failure
        delay: 5s

# configs:
#   # to avoid changes to the original verdaccio image, we import the healthcheck script using configs
#   verdaccio-healthcheck:
#     file: verdaccio-healthcheck

networks:
  back-tier:
    external: true

volumes:
  verdacciodata:
    external: true
