version: "3.9"

services:

  mysql:
    image: "mysql:${IMAGE_TAG}"
    ports:
      - target: 3306
        published: ${PUBLISHED_PORT}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
      - type: bind
        source: ./initdb
        target: /docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      back-tier:
        aliases:
          - mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "/etc/init.d/mysql status"]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role=manager"
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  back-tier:
    external: true

volumes:
  mysqldata:
    external: true
