--- 

version: "3.3"

services: 

  postgres: 
    image: postgres:10-alpine
    ports: 
      - 5432:5432
    volumes: 
      - "postgresdata:/var/lib/postgresql/data"
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ZGQ2NjdhOTcyYzE2ZTI3ZjYyYTE3OTIz
      POSTGRES_USER: postgres
    networks: 
      back-tier: 
        aliases: 
          - postgres
    deploy: 
      replicas: 1
      resources: 
        limits: 
          cpus: "0.1"
          memory: 500m
      restart_policy: 
        condition: on-failure
        delay: 5s

networks: 
  back-tier: 
    external: true

volumes: 
  postgresdata: 
    external: true
