---

version: "3.3"

services:

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    networks:
      back-tier:
        aliases:
          - redis
    volumes:
      - redisdata:/data
    configs:
    # to avoid changes to the original image, we import the healthcheck script using configs
      - redis-healthcheck
    healthcheck:
      test: ["CMD", "bash", "/redis-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300m
      restart_policy:
        condition: on-failure
        delay: 10s

configs:
  # to avoid changes to the original image, we import the healthcheck script using configs
  redis-healthcheck:
    file: redis-healthcheck

networks:
  back-tier:
    external: true

volumes:
  redisdata:
    external: true
